name: Keep Render Site Awake

on:
  schedule:
    - cron: "*/30 * * * *"  # Toutes les 30 minutes (UTC)
  workflow_dispatch:

jobs:
  ping-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run ping script
        run: python ping.py
